"""Inicializando base de datos

Revision ID: b002b7dbb0f4
Revises: 
Create Date: 2025-01-30 12:23:14.281461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b002b7dbb0f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=1), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name')
    )
    op.create_table('sector_zone_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=1), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sector_zone_image')
    op.drop_table('product_association')
    # ### end Alembic commands ###
